spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    #url: jdbc:mysql://localhost:3306/gzjc?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    url: jdbc:mysql://localhost:3306/dayueke-wx?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root


